css_path=	www/style

less_path=	www/style/less

all:
	lessc $(less_path)/accueil.less > $(css_path)/accueil.css
	lessc $(less_path)/about.less > $(css_path)/about.css
	lessc $(less_path)/footer.less > $(css_path)/footer.css
	lessc $(less_path)/slider.less > $(css_path)/slider.css
	lessc $(less_path)/project.less > $(css_path)/project.css
